update

diff --git a/.github/workflows/add-users.yaml b/.github/workflows/add-users.yaml
--- a/.github/workflows/add-users.yaml
+++ b/.github/workflows/add-users.yaml
@@ -24,35 +24,36 @@ jobs:
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-    # - name: Add user to Azure AD group
-    #   run: |
-    #     USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
-    #     echo "=========="
-    #     az ad user list
-    #     echo "============="
-    #     az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv
-    #     echo "================"
-    #     echo "User ID: '$USER_ID'"
-    #     if [ -z "$USER_ID" ]; then
-    #       echo "User not found for email $USER_ID"
-    #       exit 1
-    #     else
-    #       az ad group member add --group ruwan-eng-incident --member-id $USER_ID
-    #     fi
-    #   shell: bash
-
-    - name: Retrive User ObjectID from Entra
-      run:  USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
-   
-    - name: Add User to Group
+    - name: Add user to Azure AD group
       id: adduserentra
       run: |
+        USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
+        echo "=========="
+        az ad user list
+        echo "============="
+        az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv
+        echo "================"
+        echo "User ID: '$USER_ID'"
         if [ -z "$USER_ID" ]; then
-            echo "User not found for email $USER_ID"
-            exit 1
-          else
-            az ad group member add --group ruwan-eng-incident --member-id $USER_ID
-          fi
+          echo "User not found for email $USER_ID"
+          exit 1
+        else
+          az ad group member add --group ruwan-eng-incident --member-id $USER_ID
+        fi
+      shell: bash
+
+    # - name: Retrive User ObjectID from Entra
+    #   run:  USER_ID=$(az ad user list --filter "mail eq '${{ github.event.inputs.user_id }}'" --query "[].id" -o tsv)
+   
+    # - name: Add User to Group
+    #   id: adduserentra
+    #   run: |
+    #     if [ -z "$USER_ID" ]; then
+    #         echo "User not found for email $USER_ID"
+    #         exit 1
+    #       else
+    #         az ad group member add --group ruwan-eng-incident --member-id $USER_ID
+    #       fi
 
     - name: Post to a Slack channel eng-mon-incident-group-users
       id: slack
